Disable usage banner for e2e tests
metalbear-co/mirrord-intellij pull request #74
Opened 2023-08-04 19:38 UTC by infiniteregrets

2023-08-05 17:25 UTC, aviramha approved these changes

2023-08-05 18:18 UTC, eyalb181 approved these changes

2023-08-07 16:30 UTC, Razz4780 requested changes

2023-08-07 16:30 UTC, Razz4780 commented on modules/core/src/main/kotlin/com/metalbear/mirrord/MirrordUsageBanner.kt
> +        if (!MirrordSettingsState.instance.mirrordState.showUsageBanner || !System.getProperty("mirrord.usage.banner").toBoolean()) {
Now the banner is never shown, `System.getProperty("mirrord.usage.banner").toBoolean()` evaluates to `false` if the property is not set. I suggest using something like `mirrord.usage.nobanner`

2023-08-08 09:55 UTC, Razz4780 approved these changes

2023-08-09 04:13 UTC, merged